# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/plugin_config_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PluginConfigDialog(object):
    def setupUi(self, PluginConfigDialog):
        PluginConfigDialog.setObjectName("PluginConfigDialog")
        PluginConfigDialog.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(PluginConfigDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(PluginConfigDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(PluginConfigDialog)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(PluginConfigDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PluginConfigDialog)
        self.buttonBox.accepted.connect(PluginConfigDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(PluginConfigDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PluginConfigDialog)

    def retranslateUi(self, PluginConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        PluginConfigDialog.setWindowTitle(_translate("PluginConfigDialog", "Plugin Configuration"))
        self.label.setText(_translate("PluginConfigDialog", "Configure Plugin Settings"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("PluginConfigDialog", "Plugin"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("PluginConfigDialog", "Status"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("PluginConfigDialog", "Actions"))
