# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(600, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(SettingsDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.generalTab = QtWidgets.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.formLayout = QtWidgets.QFormLayout(self.generalTab)
        self.formLayout.setObjectName("formLayout")
        self.themeLabel = QtWidgets.QLabel(self.generalTab)
        self.themeLabel.setObjectName("themeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.themeLabel)
        self.themeComboBox = QtWidgets.QComboBox(self.generalTab)
        self.themeComboBox.setObjectName("themeComboBox")
        self.themeComboBox.addItem("")
        self.themeComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.themeComboBox)
        self.languageLabel = QtWidgets.QLabel(self.generalTab)
        self.languageLabel.setObjectName("languageLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.languageLabel)
        self.languageComboBox = QtWidgets.QComboBox(self.generalTab)
        self.languageComboBox.setObjectName("languageComboBox")
        self.languageComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.languageComboBox)
        self.tabWidget.addTab(self.generalTab, "")
        self.dataTab = QtWidgets.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.dataTab)
        self.formLayout_2.setObjectName("formLayout_2")
        self.dataFolderLabel = QtWidgets.QLabel(self.dataTab)
        self.dataFolderLabel.setObjectName("dataFolderLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dataFolderLabel)
        self.dataFolderLineEdit = QtWidgets.QLineEdit(self.dataTab)
        self.dataFolderLineEdit.setObjectName("dataFolderLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dataFolderLineEdit)
        self.browseFolderButton = QtWidgets.QPushButton(self.dataTab)
        self.browseFolderButton.setObjectName("browseFolderButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.browseFolderButton)
        self.tabWidget.addTab(self.dataTab, "")
        self.pluginsTab = QtWidgets.QWidget()
        self.pluginsTab.setObjectName("pluginsTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pluginsTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.configurePluginsButton = QtWidgets.QPushButton(self.pluginsTab)
        self.configurePluginsButton.setObjectName("configurePluginsButton")
        self.verticalLayout_2.addWidget(self.configurePluginsButton)
        self.pluginListWidget = QtWidgets.QListWidget(self.pluginsTab)
        self.pluginListWidget.setObjectName("pluginListWidget")
        self.verticalLayout_2.addWidget(self.pluginListWidget)
        self.tabWidget.addTab(self.pluginsTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(SettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.themeLabel.setText(_translate("SettingsDialog", "Theme:"))
        self.themeComboBox.setItemText(0, _translate("SettingsDialog", "Light"))
        self.themeComboBox.setItemText(1, _translate("SettingsDialog", "Dark"))
        self.languageLabel.setText(_translate("SettingsDialog", "Language:"))
        self.languageComboBox.setItemText(0, _translate("SettingsDialog", "English"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generalTab), _translate("SettingsDialog", "General"))
        self.dataFolderLabel.setText(_translate("SettingsDialog", "Data Folder:"))
        self.browseFolderButton.setText(_translate("SettingsDialog", "Browse..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), _translate("SettingsDialog", "Data"))
        self.configurePluginsButton.setText(_translate("SettingsDialog", "Configure Plugins"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pluginsTab), _translate("SettingsDialog", "Plugins"))
