# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\personProjectWizard.ui'
#
# Created: Fri Jan 31 15:30:24 2014
#      by: PyQt5 UI code generator 5.15.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_personProjectWizard(object):
    def setupUi(self, personProjectWizard):
        personProjectWizard.setObjectName(_fromUtf8("personProjectWizard"))
        personProjectWizard.resize(898, 702)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/creepy/user")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        personProjectWizard.setWindowIcon(icon)
        personProjectWizard.setWizardStyle(QtWidgets.QWizard.ClassicStyle)
        personProjectWizard.setOptions(QtWidgets.QWizard.HelpButtonOnRight)
        self.personProjectWizardPage1 = QtWidgets.QWizardPage()
        self.personProjectWizardPage1.setObjectName(_fromUtf8("personProjectWizardPage1"))
        self.gridLayoutWidget = QtWidgets.QWidget(self.personProjectWizardPage1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 861, 591))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.personProjectDescriptionValue = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.personProjectDescriptionValue.setPlainText(_fromUtf8(""))
        self.personProjectDescriptionValue.setObjectName(_fromUtf8("personProjectDescriptionValue"))
        self.gridLayout_3.addWidget(self.personProjectDescriptionValue, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 1, 1, 1)
        self.personProjectNameValue = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.personProjectNameValue.setObjectName(_fromUtf8("personProjectNameValue"))
        self.gridLayout_3.addWidget(self.personProjectNameValue, 0, 1, 1, 1)
        self.personProjectNameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.personProjectNameLabel.setEnabled(True)
        self.personProjectNameLabel.setObjectName(_fromUtf8("personProjectNameLabel"))
        self.gridLayout_3.addWidget(self.personProjectNameLabel, 0, 0, 1, 1)
        self.personProjectKeywordsValue = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.personProjectKeywordsValue.setObjectName(_fromUtf8("personProjectKeywordsValue"))
        self.gridLayout_3.addWidget(self.personProjectKeywordsValue, 1, 1, 1, 1)
        self.personProjectDescriptionLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personProjectDescriptionLabel.sizePolicy().hasHeightForWidth())
        self.personProjectDescriptionLabel.setSizePolicy(sizePolicy)
        self.personProjectDescriptionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.personProjectDescriptionLabel.setObjectName(_fromUtf8("personProjectDescriptionLabel"))
        self.gridLayout_3.addWidget(self.personProjectDescriptionLabel, 2, 0, 1, 1)
        self.personProkectKeywordsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.personProkectKeywordsLabel.setObjectName(_fromUtf8("personProkectKeywordsLabel"))
        self.gridLayout_3.addWidget(self.personProkectKeywordsLabel, 1, 0, 1, 1)
        personProjectWizard.addPage(self.personProjectWizardPage1)
        self.personProjectWizardPage2 = QtWidgets.QWizardPage()
        self.personProjectWizardPage2.setObjectName(_fromUtf8("personProjectWizardPage2"))
        self.gridLayout = QtWidgets.QGridLayout(self.personProjectWizardPage2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnAddTarget = QtWidgets.QPushButton(self.personProjectWizardPage2)
        self.btnAddTarget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnAddTarget.setStyleSheet(_fromUtf8(""))
        self.btnAddTarget.setObjectName(_fromUtf8("btnAddTarget"))
        self.horizontalLayout.addWidget(self.btnAddTarget)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 3, 1, 1)
        self.personProjectSelectedTargetsTable = QtWidgets.QTableView(self.personProjectWizardPage2)
        self.personProjectSelectedTargetsTable.setDragEnabled(False)
        self.personProjectSelectedTargetsTable.setDragDropOverwriteMode(True)
        self.personProjectSelectedTargetsTable.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.personProjectSelectedTargetsTable.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.personProjectSelectedTargetsTable.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.personProjectSelectedTargetsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.personProjectSelectedTargetsTable.setSortingEnabled(True)
        self.personProjectSelectedTargetsTable.setObjectName(_fromUtf8("personProjectSelectedTargetsTable"))
        self.personProjectSelectedTargetsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.personProjectSelectedTargetsTable.horizontalHeader().setStretchLastSection(True)
        self.personProjectSelectedTargetsTable.verticalHeader().setVisible(False)
        self.personProjectSelectedTargetsTable.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout.addWidget(self.personProjectSelectedTargetsTable, 8, 2, 1, 2)
        self.personProjectTargetSeperatorLine = QtWidgets.QFrame(self.personProjectWizardPage2)
        self.personProjectTargetSeperatorLine.setLineWidth(4)
        self.personProjectTargetSeperatorLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.personProjectTargetSeperatorLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.personProjectTargetSeperatorLine.setObjectName(_fromUtf8("personProjectTargetSeperatorLine"))
        self.gridLayout.addWidget(self.personProjectTargetSeperatorLine, 6, 1, 1, 3)
        self.personProjectSearchResultsTable = QtWidgets.QTableView(self.personProjectWizardPage2)
        self.personProjectSearchResultsTable.setDragEnabled(True)
        self.personProjectSearchResultsTable.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.personProjectSearchResultsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.personProjectSearchResultsTable.setSortingEnabled(True)
        self.personProjectSearchResultsTable.setObjectName(_fromUtf8("personProjectSearchResultsTable"))
        self.personProjectSearchResultsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.personProjectSearchResultsTable.horizontalHeader().setStretchLastSection(True)
        self.personProjectSearchResultsTable.verticalHeader().setVisible(False)
        self.personProjectSearchResultsTable.verticalHeader().setCascadingSectionResizes(True)
        self.personProjectSearchResultsTable.verticalHeader().setMinimumSectionSize(19)
        self.personProjectSearchResultsTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.personProjectSearchResultsTable, 4, 2, 1, 2)
        self.personProjectSearchForLabel = QtWidgets.QLabel(self.personProjectWizardPage2)
        self.personProjectSearchForLabel.setObjectName(_fromUtf8("personProjectSearchForLabel"))
        self.gridLayout.addWidget(self.personProjectSearchForLabel, 0, 0, 1, 2)
        self.personProjectSearchResultsLabel = QtWidgets.QLabel(self.personProjectWizardPage2)
        self.personProjectSearchResultsLabel.setObjectName(_fromUtf8("personProjectSearchResultsLabel"))
        self.gridLayout.addWidget(self.personProjectSearchResultsLabel, 4, 0, 1, 1)
        self.personProjectSelectedTargetsLabel = QtWidgets.QLabel(self.personProjectWizardPage2)
        self.personProjectSelectedTargetsLabel.setObjectName(_fromUtf8("personProjectSelectedTargetsLabel"))
        self.gridLayout.addWidget(self.personProjectSelectedTargetsLabel, 8, 0, 1, 1)
        self.personProjectSearchInLabel = QtWidgets.QLabel(self.personProjectWizardPage2)
        self.personProjectSearchInLabel.setObjectName(_fromUtf8("personProjectSearchInLabel"))
        self.gridLayout.addWidget(self.personProjectSearchInLabel, 1, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 2, 1, 1)
        self.personProjectSearchForDetailsLabel = QtWidgets.QLabel(self.personProjectWizardPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personProjectSearchForDetailsLabel.sizePolicy().hasHeightForWidth())
        self.personProjectSearchForDetailsLabel.setSizePolicy(sizePolicy)
        self.personProjectSearchForDetailsLabel.setObjectName(_fromUtf8("personProjectSearchForDetailsLabel"))
        self.gridLayout.addWidget(self.personProjectSearchForDetailsLabel, 0, 3, 1, 1)
        self.personProjectAvailablePluginsScrollArea = QtWidgets.QScrollArea(self.personProjectWizardPage2)
        self.personProjectAvailablePluginsScrollArea.setWidgetResizable(True)
        self.personProjectAvailablePluginsScrollArea.setObjectName(_fromUtf8("personProjectAvailablePluginsScrollArea"))
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 91))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.personProjectAvailablePluginsListView = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.personProjectAvailablePluginsListView.setObjectName(_fromUtf8("personProjectAvailablePluginsListView"))
        self.verticalLayout.addWidget(self.personProjectAvailablePluginsListView)
        self.personProjectAvailablePluginsScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.personProjectAvailablePluginsScrollArea, 1, 2, 1, 2)
        self.personProjectSearchForValue = QtWidgets.QLineEdit(self.personProjectWizardPage2)
        self.personProjectSearchForValue.setObjectName(_fromUtf8("personProjectSearchForValue"))
        self.gridLayout.addWidget(self.personProjectSearchForValue, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.personProjectSearchButton = QtWidgets.QPushButton(self.personProjectWizardPage2)
        self.personProjectSearchButton.setDefault(True)
        self.personProjectSearchButton.setObjectName(_fromUtf8("personProjectSearchButton"))
        self.horizontalLayout_2.addWidget(self.personProjectSearchButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 9, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.btnRemoveTarget = QtWidgets.QPushButton(self.personProjectWizardPage2)
        self.btnRemoveTarget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnRemoveTarget.setStyleSheet(_fromUtf8(""))
        self.btnRemoveTarget.setObjectName(_fromUtf8("btnRemoveTarget"))
        self.horizontalLayout_3.addWidget(self.btnRemoveTarget)
        self.gridLayout.addLayout(self.horizontalLayout_3, 9, 3, 1, 1)
        personProjectWizard.addPage(self.personProjectWizardPage2)
        self.personProjectWizardPage3 = QtWidgets.QWizardPage()
        self.personProjectWizardPage3.setObjectName(_fromUtf8("personProjectWizardPage3"))
        self.personProjectWizardSearchConfigPluginsList = QtWidgets.QListView(self.personProjectWizardPage3)
        self.personProjectWizardSearchConfigPluginsList.setGeometry(QtCore.QRect(0, 0, 256, 531))
        self.personProjectWizardSearchConfigPluginsList.setObjectName(_fromUtf8("personProjectWizardSearchConfigPluginsList"))
        self.searchConfiguration = QtWidgets.QStackedWidget(self.personProjectWizardPage3)
        self.searchConfiguration.setGeometry(QtCore.QRect(260, 0, 591, 531))
        self.searchConfiguration.setObjectName(_fromUtf8("searchConfiguration"))
        personProjectWizard.addPage(self.personProjectWizardPage3)
        self.personProjectWizardPage4 = QtWidgets.QWizardPage()
        self.personProjectWizardPage4.setObjectName(_fromUtf8("personProjectWizardPage4"))
        self.gridLayout_2 = QtWidgets.QGridLayout(self.personProjectWizardPage4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        personProjectWizard.addPage(self.personProjectWizardPage4)

        self.retranslateUi(personProjectWizard)
        QtCore.QMetaObject.connectSlotsByName(personProjectWizard)

    def retranslateUi(self, personProjectWizard):
        personProjectWizard.setWindowTitle(QtWidgets.QApplication.translate("personProjectWizard", "New Person Project", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectWizardPage1.setTitle(QtWidgets.QApplication.translate("personProjectWizard", "Step 1 - Set Project Metadata", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectWizardPage1.setSubTitle(QtWidgets.QApplication.translate("personProjectWizard", "Add project related information", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectNameValue.setPlaceholderText(QtWidgets.QApplication.translate("personProjectWizard", "Add a name for your project", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectNameLabel.setText(QtWidgets.QApplication.translate("personProjectWizard", "Project Name ", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectKeywordsValue.setPlaceholderText(QtWidgets.QApplication.translate("personProjectWizard", "Add comma seperated keywords for your project", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectDescriptionLabel.setText(QtWidgets.QApplication.translate("personProjectWizard", "Description", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProkectKeywordsLabel.setText(QtWidgets.QApplication.translate("personProjectWizard", "Keywords", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectWizardPage2.setTitle(QtWidgets.QApplication.translate("personProjectWizard", "Step 2 - Set the target", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectWizardPage2.setSubTitle(QtWidgets.QApplication.translate("personProjectWizard", "Search for the person you want to track using the available plugins and add it to the <font color=\"red\">selected targets</font> by drag and drop or by clicking \"Add To Targets\"", None, QtWidgets.QApplication.UnicodeUTF8))
        self.btnAddTarget.setText(QtWidgets.QApplication.translate("personProjectWizard", "Add To Targets", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectSearchForLabel.setText(QtWidgets.QApplication.translate("personProjectWizard", "<html><head/><body><p><span style=\" font-weight:600;\">Search for</span></p></body></html>", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectSearchResultsLabel.setText(QtWidgets.QApplication.translate("personProjectWizard", "<html><head/><body><p><span style=\" font-weight:600;\">Search Results </span></p></body></html>", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectSelectedTargetsLabel.setText(QtWidgets.QApplication.translate("personProjectWizard", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Selected Targets</span></p></body></html>", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectSearchInLabel.setText(QtWidgets.QApplication.translate("personProjectWizard", "<html><head/><body><p><span style=\" font-weight:600;\">Search In</span></p></body></html>", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectSearchForDetailsLabel.setText(QtWidgets.QApplication.translate("personProjectWizard", "Search by username, mail, full name, id", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectSearchButton.setToolTip(QtWidgets.QApplication.translate("personProjectWizard", "Search for targets in the selected plugins", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectSearchButton.setText(QtWidgets.QApplication.translate("personProjectWizard", "Search", None, QtWidgets.QApplication.UnicodeUTF8))
        self.btnRemoveTarget.setText(QtWidgets.QApplication.translate("personProjectWizard", "Remove Selected", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectWizardPage3.setTitle(QtWidgets.QApplication.translate("personProjectWizard", "Step 3 - Set Parameters", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectWizardPage3.setSubTitle(QtWidgets.QApplication.translate("personProjectWizard", "Provide the necessary search parameters for the plugins you are using", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectWizardPage4.setTitle(QtWidgets.QApplication.translate("personProjectWizard", "Step 4  - Finalize Project", None, QtWidgets.QApplication.UnicodeUTF8))
        self.personProjectWizardPage4.setSubTitle(QtWidgets.QApplication.translate("personProjectWizard", "Click Finish to save the Project Configuration ", None, QtWidgets.QApplication.UnicodeUTF8))

import creepy_resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    personProjectWizard = QtWidgets.QWizard()
    ui = Ui_personProjectWizard()
    ui.setupUi(personProjectWizard)
    personProjectWizard.show()
    sys.exit(app.exec_())

